using Demo.Sealed;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Partial
{
    // Auto Generated File By EF-Core
    internal partial class Employee : Parent
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }

        public partial void Print();
        public void DoSomeThind()
        {
            Console.WriteLine("Hello From AutoGenerated File");
            Print();
        }
    }
}
